Repository reciprocity/zen-ui, pull requests merged in 2021-04, with the labels that each got.

#274 PLAT-1605: Add title and hyperlink to tooltip
  cypress/integration/visual/tooltip.e2e.js
  src/components.d.ts
  src/components/zen-tooltip/test/zen-tooltip.spec.tsx
  src/components/zen-tooltip/zen-tooltip.scss
  src/components/zen-tooltip/zen-tooltip.stories.mdx
  src/components/zen-tooltip/zen-tooltip.tsx
Labels: priority:medium, semver:feature, size:small

#280 PLAT-1611: inputs: add size prop
  .storybook/helpers/utils.js
  .storybook/preview.scss
  cypress/integration/visual/date-picker.e2e.js
  cypress/integration/visual/dropdown.e2e.js
  cypress/integration/visual/dropdownOption.e2e.js
  cypress/integration/visual/input.e2e.js
  cypress/snapshots/visual/date-picker.e2e.js/Date-picker visual tests -- Verifies story--forms-date-picker--default-story.snap.png
  cypress/snapshots/visual/date-picker.e2e.js/Date-picker visual tests -- Verifies story--forms-date-picker--initial.snap.png
  cypress/snapshots/visual/date-picker.e2e.js/Date-picker visual tests -- Verifies story--forms-date-picker--story-sizes.snap.png
  cypress/snapshots/visual/date-picker.e2e.js/field-story--forms-date-picker--default-story.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/Dropdown visual tests -- Verifies opened dropdown in story--forms-dropdown-dropdown--button.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/Dropdown visual tests -- Verifies opened dropdown in story--forms-dropdown-dropdown--invite-people.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/Dropdown visual tests -- Verifies opened dropdown in story--forms-dropdown-dropdown--story-form-group.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/Dropdown visual tests -- Verifies opened dropdown in story--forms-dropdown-dropdown--story-sizes.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/field-story--forms-dropdown-dropdown--default-story.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/field-story--forms-dropdown-dropdown--invite-people.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/field-story--forms-dropdown-dropdown--story-form-group.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/field-story--forms-dropdown-dropdown--story-sizes.snap.png
  cypress/snapshots/visual/dropdownOption.e2e.js/Dropdown option visual tests -- Verifies story--forms-dropdown-dropdown-option--default-story.snap.png
  cypress/snapshots/visual/dropdownOption.e2e.js/Dropdown option visual tests -- Verifies story--forms-dropdown-dropdown-option--slots.snap.png
  cypress/snapshots/visual/dropdownOption.e2e.js/Dropdown option visual tests -- Verifies story--forms-dropdown-dropdown-option--story-sizes.snap.png
  cypress/snapshots/visual/input.e2e.js/Input visual tests -- Verifies story--forms-input--default-story.snap.png
  cypress/snapshots/visual/input.e2e.js/Input visual tests -- Verifies story--forms-input--story-form-group.snap.png
  cypress/snapshots/visual/input.e2e.js/Input visual tests -- Verifies story--forms-input--story-sizes.snap.png
  cypress/snapshots/visual/input.e2e.js/Input visual tests -- Verifies story--forms-input--story-with-leading-and-trailing-slots.snap.png
  cypress/snapshots/visual/input.e2e.js/Input visual tests -- Verifies story--forms-input--story-with-leading-slot.snap.png
  cypress/snapshots/visual/input.e2e.js/Input visual tests -- Verifies story--forms-input--story-with-trailing-slot.snap.png
  cypress/snapshots/visual/text.e2e.js/Text visual tests -- Verifies story--typography-text--label.snap.png
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
  src/components/zen-date-picker/zen-date-picker.stories.mdx
  src/components/zen-date-picker/zen-date-picker.tsx
  src/components/zen-dropdown/test/zen-dropdown.spec.tsx
  src/components/zen-dropdown/zen-dropdown.scss
  src/components/zen-dropdown/zen-dropdown.stories.mdx
  src/components/zen-dropdown/zen-dropdown.tsx
  src/components/zen-input/test/zen-input.spec.tsx
  src/components/zen-input/zen-input.scss
  src/components/zen-input/zen-input.stories.mdx
  src/components/zen-input/zen-input.tsx
  src/components/zen-menu-item/zen-option.scss
  src/components/zen-menu-item/zen-option.stories.mdx
  src/components/zen-menu-item/zen-option.tsx
  src/components/zen-popover/zen-popover.scss
Labels: semver:feature, size:large

#284 QUICK: Fix Firefox storybook overlapping
  .storybook/preview.scss
Labels: priority:high, size:small

#287 PLAT-1612: Updated zen-toggle styles
  src/components/zen-toggle/zen-toggle.scss
Labels: size:small

#290 QUICK: Add documentation about conventional commits
  docs/contributing.md
  docs/conventional-commits.md
Labels: priority:low, semver:none, size:small

#288 PLAT-1696: Added focusInput method to zen-textarea
  src/components.d.ts
  src/components/zen-textarea/zen-textarea.tsx
Labels: priority:high, semver:feature, size:small

#286 PLAT-1659: Validate the use of EM units on ZenUI
  cypress/snapshots/visual/progress-tracker.e2e.js/Progress tracker visual tests -- Verifies story--navigation-progress-tracker--default-story.snap.png
  src/components/zen-divider/zen-divider.scss
  src/components/zen-progress-tracker/zen-progress-tracker.scss
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/zen-styles/variables.scss
Labels: priority:medium, semver:fix, size:small

#294 PLAT-1607: Remove size lg from avatar-icon
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--graphics-avatar-avatar-details--default-story.snap.png
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--graphics-avatar-avatar-details--story-variants.snap.png
  cypress/snapshots/visual/avatarIcon.e2e.js/Avatar icon visual tests -- Verifies story--graphics-avatar-avatar-icon--default-story.snap.png
  cypress/snapshots/visual/avatarIcon.e2e.js/Avatar icon visual tests -- Verifies story--graphics-avatar-avatar-icon--story-avatar-sizes.snap.png
  cypress/snapshots/visual/avatarIcon.e2e.js/Avatar icon visual tests -- Verifies story--graphics-avatar-avatar-icon--story-avatar-variants.snap.png
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-avatar-group/zen-avatar-group.tsx
  src/components/zen-avatar-icon/zen-avatar-icon.stories.mdx
  src/components/zen-avatar-icon/zen-avatar-icon.tsx
  src/components/zen-icon/zen-icon.tsx
Labels: priority:high, semver:breaking, size:small

#297 PLAT-1627: Table component full span elements overlap issue
  cypress/integration/visual/table.e2e.js
  cypress/integration/visual/tableHeader.e2e.js
  cypress/integration/visual/tableRow.e2e.js
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--lists-table-table--default-story.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--lists-table-table--no-header.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--lists-table-table--sticky-header.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--lists-table-table--with-fragments.snap.png
  cypress/snapshots/visual/tableRow.e2e.js/Table row visual tests -- Verifies story--lists-table-row--default-story.snap.png
  src/.eslintrc.js
  src/components.d.ts
  src/components/zen-button/zen-button.tsx
  src/components/zen-sortable-item/zen-sortable-item.stories.mdx
  src/components/zen-table-cell/zen-table-cell.scss
  src/components/zen-table-cell/zen-table-cell.tsx
  src/components/zen-table-header-cell/test/zen-table-header-cell.spec.tsx
  src/components/zen-table-header-cell/zen-table-header-cell.scss
  src/components/zen-table-header-cell/zen-table-header-cell.tsx
  src/components/zen-table-header/test/zen-table-header.spec.tsx
  src/components/zen-table-header/zen-table-header.scss
  src/components/zen-table-header/zen-table-header.stories.mdx
  src/components/zen-table-header/zen-table-header.tsx
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table-row/zen-table-row.scss
  src/components/zen-table-row/zen-table-row.stories.mdx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/test/zen-table.spec.tsx
  src/components/zen-table/zen-table.scss
  src/components/zen-table/zen-table.stories.mdx
  src/components/zen-table/zen-table.tsx
Labels: priority:high, size:large

#302 PLAT-1772: Fix for initials not displayed correctly
  cypress/integration/visual/avatarGroup.e2e.js
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-avatar-details/zen-avatar-details.tsx
  src/components/zen-avatar-group/zen-avatar-group.stories.mdx
  src/components/zen-avatar-icon/zen-avatar-icon.tsx
  src/components/zen-avatar/zen-avatar.tsx
Labels: priority:high, semver:feature, size:small

#301 PLAT-1755: Add tabs component
  cypress/integration/visual/tabs.e2e.js
  cypress/snapshots/visual/tabs.e2e.js/Tabs visual tests -- Verifies story--in-progress-tabs-tabs--default-story.snap.png
  cypress/snapshots/visual/tabs.e2e.js/Tabs visual tests -- Verifies story--navigation-tabs-tabs--default-story.snap.png
  src/components.d.ts
  src/components/zen-tab/test/zen-tab.spec.tsx
  src/components/zen-tab/zen-tab.scss
  src/components/zen-tab/zen-tab.stories.mdx
  src/components/zen-tab/zen-tab.tsx
  src/components/zen-tabs/test/zen-tabs.spec.tsx
  src/components/zen-tabs/zen-tabs.scss
  src/components/zen-tabs/zen-tabs.stories.mdx
  src/components/zen-tabs/zen-tabs.stories.ts
  src/components/zen-tabs/zen-tabs.tsx
Labels: priority:medium, semver:feature, size:small

#303 Next Breaking
  cypress/integration/visual/drawer.e2e.js
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--graphics-avatar-avatar-details--default-story.snap.png
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--graphics-avatar-avatar-details--story-variants.snap.png
  cypress/snapshots/visual/avatarIcon.e2e.js/Avatar icon visual tests -- Verifies story--graphics-avatar-avatar-icon--default-story.snap.png
  cypress/snapshots/visual/avatarIcon.e2e.js/Avatar icon visual tests -- Verifies story--graphics-avatar-avatar-icon--story-avatar-sizes.snap.png
  cypress/snapshots/visual/avatarIcon.e2e.js/Avatar icon visual tests -- Verifies story--graphics-avatar-avatar-icon--story-avatar-variants.snap.png
  cypress/snapshots/visual/button.e2e.js/Button visual tests -- Verifies story--forms-button--default-story.snap.png
  cypress/snapshots/visual/button.e2e.js/Button visual tests -- Verifies story--forms-button--story-simple.snap.png
  cypress/snapshots/visual/drawer.e2e.js/Drawer visual tests -- Verifies story--containers-drawer--default-story.snap.png
  cypress/snapshots/visual/drawer.e2e.js/Drawer visual tests -- Verifies that drawer closes on close icon story--containers-drawer--default-story.snap.png
  cypress/snapshots/visual/drawer.e2e.js/Drawer visual tests -- Verifies that drawer opens story--containers-drawer--default-story.snap.png
  cypress/snapshots/visual/drawer.e2e.js/Drawer visual tests -- Verifies that we can set position and drawer opens story--containers-drawer--default-story.snap.png
  cypress/snapshots/visual/tooltip.e2e.js/Tooltip visual tests -- Verifies story--notifications-tooltip--scrollable.snap.png
  src/componentTemplate.stories.mdx.sample
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-avatar-group/zen-avatar-group.tsx
  src/components/zen-avatar-icon/zen-avatar-icon.stories.mdx
  src/components/zen-avatar-icon/zen-avatar-icon.tsx
  src/components/zen-button/test/zen-button.spec.tsx
  src/components/zen-button/types.tsx
  src/components/zen-button/zen-button.scss
  src/components/zen-button/zen-button.stories.mdx
  src/components/zen-button/zen-button.tsx
  src/components/zen-drawer/zen-drawer.tsx
  src/components/zen-icon/zen-icon.tsx
  src/components/zen-modal/zen-modal.stories.mdx
  src/components/zen-modal/zen-modal.tsx
  src/components/zen-popover/zen-popover.stories.mdx
  src/components/zen-tooltip/zen-tooltip.stories.mdx
Labels: feature branch, semver:breaking

#308 QUICK-FIX: item of vertical zen-space should not have right margins!
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--graphics-avatar-avatar-details--story-variants.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/Dropdown visual tests -- Verifies opened dropdown in story--forms-dropdown-dropdown--story-form-group.snap.png
  cypress/snapshots/visual/dropdown.e2e.js/field-story--forms-dropdown-dropdown--story-form-group.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--aligns-column-horz.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--aligns-column-vert.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--aligns-horz.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--aligns-vert.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--children.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--default-story.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--paddings.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--containers-space--sizes.snap.png
  src/components/zen-space/zen-space.scss
Labels: priority:high, size:small

#304 PLAT-1796: Table: Make sure table structure and state is always correct
  cypress/integration/visual/table.e2e.js
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--lists-table-table--default-story.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--tables-table--default-story.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--tables-table--no-header.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--tables-table--selectable.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--tables-table--sticky-header.snap.png
  cypress/snapshots/visual/table.e2e.js/Table visual tests -- Verifies story--tables-table--with-fragments.snap.png
  src/components.d.ts
  src/components/helpers/helpers.ts
  src/components/helpers/jest.ts
  src/components/zen-animate/test/zen-animate.spec.tsx
  src/components/zen-dropdown/test/zen-dropdown.spec.tsx
  src/components/zen-table-cell/zen-table-cell.scss
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/test/zen-table.spec.tsx
  src/components/zen-table/zen-table-helpers.tsx
  src/components/zen-table/zen-table.stories.mdx
  src/components/zen-table/zen-table.tsx
Labels: priority:high, size:medium

#307 PLAT-1805: Progress tracker labels now have white-space nowrap style
  src/components/zen-progress-tracker/zen-progress-tracker.scss
Labels: priority:high, semver:fix, size:small

#305 PLAT-1798: Table: Move header updating to zen-table.tsx
  src/components.d.ts
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/zen-table-helpers.tsx
Labels: priority:high, size:small

#309 PLAT-1735: Storybook: Mark $props as readonly in props table
  .storybook/helpers/argTypes.js
  .storybook/preview.scss
  CHANGELOG.md
  cypress/integration/visual/avatarGroup.e2e.js
  docs/components-guidelines.md
  package.json
  src/components.d.ts
  src/components/zen-progress-tracker/zen-progress-tracker.scss
  src/components/zen-tabs/zen-tabs.scss
  src/stories/components/docs-table/docs-table.tsx
Labels: priority:high, size:small

#310 PLAT-1799: Table: Make private props readonly
  src/components.d.ts
  src/components/zen-table-cell/zen-table-cell.scss
  src/components/zen-table-cell/zen-table-cell.stories.mdx
  src/components/zen-table-cell/zen-table-cell.tsx
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table-row/zen-table-row.stories.mdx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/zen-table-helpers.tsx
  src/components/zen-table/zen-table.stories.mdx
  src/components/zen-table/zen-table.tsx
Labels: priority:high, size:medium

#314 PLAT-1806: Fix avatar image url missing from properties
  cypress/snapshots/visual/avatarGroup.e2e.js/Avatar group popover - single user.snap.png
  src/components.d.ts
  src/components/zen-avatar-details/zen-avatar-details.tsx
  src/components/zen-avatar-group/zen-avatar-group.stories.mdx
  src/components/zen-avatar/zen-avatar.tsx
Labels: priority:medium, semver:fix, size:small

#312 PLAT-1270: Generate && Publish React bindings
  .circleci/config.yml
  .eslintignore
  .gitignore
  .prettierignore
  package.json
  react/.npmrc
  react/package.json
  react/publish.ts
  react/src/index.ts
  react/transform.ts
  react/tsconfig.json
  react/utils.ts
  react/yarn.lock
  src/components.d.ts
  src/components/zen-space/zen-space.tsx
  src/stories/components/html-playground/html-playground.tsx
  src/stories/getting_started.stories.mdx
  stencil.config.ts
  yarn.lock
Labels: priority:medium, semver:fix, size:large

#300 PLAT-1691: Updated zen-option mouseover hover style and remove keyboard focused style when mouseover
  src/components/zen-menu-item/zen-option.scss
  src/components/zen-menu-item/zen-option.tsx
Labels: question, semver:fix, size:small

#318 PLAT-1794: Test: Fix zen-table tests errors
  src/components/helpers/jest.ts
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/test/zen-table.spec.tsx
Labels: size:small

#306 PLAT-1773: When clear button is clicked on zen-input a change event is triggered
  src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
  src/components/zen-date-picker/zen-date-picker.tsx
  src/components/zen-input/zen-input.tsx
Labels: priority:medium, semver:feature, size:small

#320 PLAT-1800: Fix types on the tests
  .husky/pre-push
  cypress/tsconfig.json
  package.json
  src/.eslintrc.js
  src/components/helpers/jest.ts
  src/components/helpers/tests/animations.spec.tsx
  src/components/zen-animate/test/zen-animate.spec.tsx
  src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
  src/components/zen-breadcrumbs/test/zen-breadcrumbs.spec.tsx
  src/components/zen-date-picker/tests/date-helpers.spec.ts
  src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
  src/components/zen-dropdown/test/zen-dropdown.spec.tsx
  src/components/zen-input/test/zen-input.spec.tsx
  src/components/zen-modal/test/zen-modal.spec.tsx
  src/components/zen-modal/test/zen-modals-service.spec.tsx
  src/components/zen-notification/test/zen-notification.spec.tsx
  src/components/zen-panel/test/zen-panel.spec.tsx
  src/components/zen-popover/test/zen-popover.spec.tsx
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table/test/zen-table.spec.tsx
  src/components/zen-tooltip/test/zen-tooltip.spec.tsx
  tsconfig.json
Labels: medium, priority:medium, semver:none

#321 PLAT-1774: Remove tooltips variants
  cypress/integration/visual/tooltip.e2e.js
  cypress/snapshots/visual/tooltip.e2e.js/Tooltip visual tests -- Verifies story--notifications-tooltip--scrollable.snap.png
  cypress/snapshots/visual/tooltip.e2e.js/Tooltip visual tests -- Verifies story--notifications-tooltip--slot.snap.png
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-tooltip/test/zen-tooltip.spec.tsx
  src/components/zen-tooltip/zen-tooltip.stories.mdx
  src/components/zen-tooltip/zen-tooltip.tsx
Labels: priority:medium, semver:breaking, small

#331 PLAT-1977: Export helper types & add missing annotations
  package.json
  src/components.d.ts
  src/components/zen-card/zen-card.tsx
  src/components/zen-checkbox/zen-checkbox.tsx
  src/components/zen-date-picker/zen-date-picker.tsx
  src/components/zen-drawer/zen-drawer.tsx
  src/components/zen-dropdown/zen-dropdown.tsx
  src/components/zen-input/zen-input.tsx
  src/components/zen-modal/zen-modal.tsx
  src/components/zen-radio/zen-radio.tsx
  src/components/zen-text/zen-text.tsx
  src/components/zen-textarea/zen-textarea.tsx
  src/components/zen-toggle/zen-toggle.tsx
  src/interface.d.ts
  src/stories/components/html-playground/html-playground.tsx
Labels: priority:low, semver:fix, size:small

#328 PLAT-1815: Add status tracker component
  cypress/integration/visual/statusTracker.e2e.js
  cypress/snapshots/visual/lozenge.e2e.js/Lozenge visual tests -- Verifies story--graphics-lozenge--story-variants.snap.png
  cypress/snapshots/visual/statusTracker.e2e.js/Status tracker visual tests -- Verifies story--navigation-status-tracker--default-story.snap.png
  cypress/snapshots/visual/statusTracker.e2e.js/Status tracker visual tests -- Verifies story--navigation-status-tracker--story-selected.snap.png
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-lozenge/zen-lozenge.scss
  src/components/zen-lozenge/zen-lozenge.stories.mdx
  src/components/zen-lozenge/zen-lozenge.tsx
  src/components/zen-status-tracker/test/zen-status-tracker.spec.tsx
  src/components/zen-status-tracker/zen-status-tracker.scss
  src/components/zen-status-tracker/zen-status-tracker.stories.mdx
  src/components/zen-status-tracker/zen-status-tracker.tsx
Labels: priority:medium, semver:feature, size:medium

#330 PLAT-1978: Change events name to to zen prefix ones
  src/components.d.ts
  src/components/zen-checkbox/zen-checkbox.tsx
  src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
  src/components/zen-date-picker/zen-date-picker.tsx
  src/components/zen-drawer/test/zen-drawer.spec.tsx
  src/components/zen-drawer/zen-drawer.tsx
  src/components/zen-dropdown/zen-dropdown.stories.mdx
  src/components/zen-dropdown/zen-dropdown.tsx
  src/components/zen-input/zen-input.tsx
  src/components/zen-modal/test/zen-modal.spec.tsx
  src/components/zen-modal/zen-modal.stories.mdx
  src/components/zen-modal/zen-modal.tsx
  src/components/zen-panel/test/zen-panel.spec.tsx
  src/components/zen-panel/zen-panel.stories.mdx
  src/components/zen-panel/zen-panel.tsx
  src/components/zen-popover/zen-popover.stories.mdx
  src/components/zen-popover/zen-popover.tsx
  src/components/zen-progress-tracker/zen-progress-tracker.stories.mdx
  src/components/zen-progress-tracker/zen-progress-tracker.tsx
  src/components/zen-radio/test/zen-radio.spec.tsx
  src/components/zen-radio/zen-radio.tsx
  src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
  src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.stories.mdx
  src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.tsx
  src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
  src/components/zen-sidebar-nav/zen-sidebar-nav.tsx
  src/components/zen-sidebar/zen-sidebar.stories.mdx
  src/components/zen-sidebar/zen-sidebar.tsx
  src/components/zen-sortable/test/zen-sortable.spec.tsx
  src/components/zen-sortable/zen-sortable.tsx
  src/components/zen-status-tracker/zen-status-tracker.tsx
  src/components/zen-tab/zen-tab.tsx
  src/components/zen-table-cell/zen-table-cell.tsx
  src/components/zen-table-row/test/zen-table-row.spec.tsx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-tabs/zen-tabs.tsx
  src/components/zen-textarea/zen-textarea.tsx
  src/components/zen-toggle/test/zen-toggle.spec.tsx
  src/components/zen-toggle/zen-toggle.tsx
  src/stories/components/html-playground/html-playground.tsx
  src/stories/components/html-playground/readme.md
Labels: priority:high, semver:breaking

#337 Properly type props of components used within other components
  src/components/helpers/helpers.ts
  src/components/helpers/types.ts
  src/components/zen-avatar-details/zen-avatar-details.tsx
  src/components/zen-avatar-group/zen-avatar-group.tsx
  src/components/zen-avatar/zen-avatar.tsx
  src/components/zen-button/zen-button.tsx
  src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
  src/components/zen-date-picker/zen-date-picker.tsx
  src/components/zen-dropdown/zen-dropdown.tsx
  src/components/zen-input/zen-input.tsx
  src/components/zen-tooltip/zen-tooltip.tsx
Labels: semver:fix, size:small
