Repository reciprocity/zen-ui, pull requests merged in 2021-03, with the labels that each got.

#240 PLAT-1461: Add indeterminate state
  src/components.d.ts
  src/components/zen-table-header/zen-table-header.scss
  src/components/zen-table-header/zen-table-header.stories.mdx
  src/components/zen-table-header/zen-table-header.tsx
  src/components/zen-table-row/zen-table-row.scss
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/zen-table.tsx
Labels: Rebase

#248 PLAT-1541: Add properties watch
  src/components.d.ts
  src/components/zen-table-header/zen-table-header.stories.mdx
  src/components/zen-table-header/zen-table-header.tsx
  src/components/zen-table-row/zen-table-row.stories.mdx
  src/components/zen-table-row/zen-table-row.tsx
  src/components/zen-table/zen-table.stories.mdx
  src/components/zen-table/zen-table.tsx
Labels: priority:high, semver:fix, size:small

#264 PLAT-1606: Add avatar details variant basic
  cypress/integration/visual/avatarDetails.e2e.js
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--icons-avatar-avatar-details--default-story.snap.png
  cypress/snapshots/visual/avatarDetails.e2e.js/Avatar details visual tests -- Verifies story--icons-avatar-avatar-details--story-variants.snap.png
  src/components.d.ts
  src/components/helpers/types.ts
  src/components/zen-avatar-details/test/zen-avatar-details.spec.tsx
  src/components/zen-avatar-details/zen-avatar-details.stories.mdx
  src/components/zen-avatar-details/zen-avatar-details.tsx
  src/components/zen-avatar-group/zen-avatar-group.tsx
Labels: priority:high, size:small

#270 PLAT-1628: Rename icons group to graphics
  .storybook/preview.js
  cypress/integration/functional/popover.e2e.js
  cypress/integration/visual/avatarDetails.e2e.js
  cypress/integration/visual/avatarGroup.e2e.js
  cypress/integration/visual/avatarIcon.e2e.js
  cypress/integration/visual/card.e2e.js
  cypress/integration/visual/divider.e2e.js
  cypress/integration/visual/drawer.e2e.js
  cypress/integration/visual/icon.e2e.js
  cypress/integration/visual/modal.e2e.js
  cypress/integration/visual/panel.e2e.js
  cypress/integration/visual/popover.e2e.js
  cypress/integration/visual/space.e2e.js
  cypress/integration/visual/spinner.e2e.js
  src/components/zen-avatar-details/zen-avatar-details.stories.mdx
  src/components/zen-avatar-group/zen-avatar-group.stories.mdx
  src/components/zen-avatar-icon/zen-avatar-icon.stories.mdx
  src/components/zen-avatar/zen-avatar.stories.mdx
  src/components/zen-card/zen-card.stories.mdx
  src/components/zen-divider/zen-divider.stories.mdx
  src/components/zen-drawer/zen-drawer.stories.mdx
  src/components/zen-icon/zen-icon.stories.mdx
  src/components/zen-modal/zen-modal.stories.mdx
  src/components/zen-panel/zen-panel.stories.mdx
  src/components/zen-popover/zen-popover.stories.mdx
  src/components/zen-skeleton/zen-skeleton.stories.mdx
  src/components/zen-sortable/test/zen-sortable.spec.tsx
  src/components/zen-space/zen-space.stories.mdx
  src/components/zen-spinner/zen-spinner.stories.mdx
Labels: priority:low, semver:none, size:small

#273 PLAT-1275: Add semantic-release
  .circleci/config.yml
  .gitignore
  .releaserc
  .storybook/changelog-base.mdx
  .storybook/changelog.js
  .storybook/main.js
  CHANGELOG.md
  docs/contributing.md
  package.json
  src/stories/changelog.stories.mdx
  yarn.lock
Labels: priority:high, semver:none, size:medium

#253 PLAT-1538: REQUEST: Control the padding on the modal slots
  cypress/snapshots/visual/modal.e2e.js/Text visual tests -- Verifies story--notifications-modal-window--paddingless.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--layout-space--children.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--layout-space--paddings.snap.png
  cypress/snapshots/visual/space.e2e.js/Button visual tests -- Verifies story--layout-space--sizes.snap.png
  src/components.d.ts
  src/components/zen-modal/test/zen-modal.spec.tsx
  src/components/zen-modal/zen-modal.scss
  src/components/zen-modal/zen-modal.stories.mdx
  src/components/zen-modal/zen-modal.tsx
  src/components/zen-space/zen-space.stories.mdx
Labels: priority:high, semver:breaking, size:medium

#278 QUICKFIX: require publish before deploy on CircleCI
  .circleci/config.yml
Labels: priority:high, semver:none, size:small

#279 QUICKFIX: Enable NPM && Fix Storybook deploy
  .circleci/config.yml
  .releaserc
Labels: priority:high, semver:fix, size:small
